logLevel: info
remindWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=5f4a82bf-ad78-4110-9b05-2bf9623690aa"
captchaWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=7b50e0c4-8a35-4f29-b652-25e1d6142c2b"
newTicketWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=901afdfc-70b7-4a11-aedc-64a32c00fff1"
parts:
  - name: "吴舒汀"
    phone: "17611213883"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=f18c4e12-60a3-4b3c-9010-c2288cd4512e"
  - name: "杨慧"
    phone: "15048008804"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=c974df4d-af7d-45a8-8694-2db288e6dc9e"
  - name: "冯浪"
    phone: "13231010331"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=edeef6e0-b990-4d1b-bdd3-4e81bdf23fa4"
  - name: "孙嘉彤"
    phone: "13630909558"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=0b6ab4c4-fc8c-4c51-9f72-50d96c845fba"
  - name: "李晓升"
    phone: "17600642139"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=4e9b2363-dc37-4ab4-aeea-d0cab43e5e6c"
  - name: "霍佳琦"
    phone: "18812012367"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=de036cd3-a5f4-4aed-ad85-a2799f0c17df"
  - name: "李斌"
    phone: "15011332744"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=80d238d4-5e03-4e46-a21e-dcffaaa05637"
  - name: "罗舒文"
    phone: "15177006671"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=832d8dd3-dd25-4531-bd2e-2c2138b7cdd9"
  - name: "谭嘉威"
    phone: "15677955548"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=28a974f2-c387-424a-a97e-a84ed212c856"
  - name: "孙凯"
    phone: "13052363610"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=8e24bac1-7a3b-48e9-9ef7-9964cb15ad43"
  - name: "杨学成"
    phone: "13760347163"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=febc9b79-c6d4-4413-9a5e-c759b722c6f9"
  - name: "王硕"
    phone: "18511280705"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=5908aa72-a6c5-4ec0-a2a6-a35f3f2a8764"
  - name: "崔星林"
    phone: "17717757039"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=44940f8d-3126-47bb-a787-ff9f833975a9"
  - name: "王奥"
    phone: "15650708414"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=e366c50c-eca5-4cec-90ee-3f45445694f3"
  - name: "王杭渝"
    phone: "17858226798"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=033862e5-d397-4539-b23e-111c23ffaf76"
  - name: "王培伦"
    phone: "15874035678"
    replyWebhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=72cfd2a3-c58c-4dea-8af3-bfb04fb209d8"