# permissions for end users to edit juggernauts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: juggernaut
    app.kubernetes.io/managed-by: kustomize
  name: juggernaut-editor-role
rules:
- apiGroups:
  - operator.oceanoperator.com
  resources:
  - juggernauts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.oceanoperator.com
  resources:
  - juggernauts/status
  verbs:
  - get
