---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operator.oceanoperator.com
  resources:
  - juggernauts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.oceanoperator.com
  resources:
  - juggernauts/finalizers
  verbs:
  - update
- apiGroups:
  - operator.oceanoperator.com
  resources:
  - juggernauts/status
  verbs:
  - get
  - patch
  - update
