apiVersion: operator.oceanoperator.com/v1
kind: Juggernaut
metadata:
  labels:
    app.kubernetes.io/name: juggernaut
    app.kubernetes.io/managed-by: kustomize
  name: juggernaut-sample
  namespace: default
spec:
  image: juggernaut:v1.3
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 50Mi
  service:
    type: ClusterIP
#  config:
#    overwrite:
#      name: config-update


